### ISSUE TITLE
Add Git LFS support

### ISSUE THREAD

**Issue by fnkr** [flathub/com.sublimemerge.App#3]
The current Flatpak does not have Git LFS binaries or filters installed.

It might be possible to reuse code from [com.axosoft.GitKraken](https://github.com/flathub/com.axosoft.GitKraken), [com.syntevo.SmartGit](https://github.com/flathub/com.syntevo.SmartGit) or [org.sparkleshare.SparkleShare](https://github.com/flathub/org.sparkleshare.SparkleShare).

**Comment by ptomato** [comment]
Could you try copying the git-lfs module from GitKraken, build a copy of sublime merge and see if it works for you?

**Comment by fnkr** [comment]
The build itself works but there are two problems:

1. The `git-lfs` binary is installed to `/app/libexec/git-core/git-lfs` but `/app/libexec/git-core` is not in `$PATH`. Should I rather install to `/app/bin` or add `/app/libexec/git-core` to `$PATH`? I could also modify the Git filters to include the full path to the binary.
2. Git filters need to be installed for LFS to work. I've added a `git lfs install --system` step, which adds the filters to `/etc/git/config` but `/etc` is not persisted. It looks like it is not possible to change the Git config location without recompiling Git: [https://git-scm.com/docs/git-config#FILES](https://git-scm.com/docs/git-config#FILES).

**Comment by ptomato** [comment]
I wonder how they get this to work in the GitKraken flatpak?

I would try adding `/app/libexec/git-core` to the path, rather than modifying the module sources. To get the git filters to work, you could install them to `~/.var/app/com.sublimemerge.App/config/git/config`, which is mentioned as a valid location in that docs page you linked (that's the value of `$XDG_CONFIG_HOME`). You would need to do this in a wrapper script to start the program, since you can't modify the user's home during the flatpak build process. We do a similar thing in flathub/com.sublimetext.three to install Package Control in the user's home: https://github.com/flathub/com.sublimetext.three/blob/master/com.sublimetext.three.yaml#L50-L61

**Comment by fnkr** [comment]
I decided to add `git-lfs install --system` to the existing wrapper script, which works fine (`/etc` is writable by the user). The `git lfs install` command does not support `$XDG_CONFIG_HOME` (`--user` would write to `~/.gitconfig`). We would have to add the filters manually, which is more likely to break in future versions. Please let me know what you think.

I don't use GitKraken but just by looking at the manifest file I unserstand that `/app/libexec/git-core` is not in `$PATH` and not referenced anywhere else. Unless GitKraken looks there by itself I don't see how it could work.
