### ISSUE TITLE
bundled git not working

### ISSUE THREAD

**Issue by sennierer** [flathub/com.sublimemerge.App#35]
I set `"git_binary": "bundled"` in my settings, but looking in my debug information
```
=== Git Version Information ===
Using Git: bundled (custom)
PATH: /app/bin:/usr/bin:/app/libexec/git-lfs
```
this doesnt seem to work. When setting to system I get the same path, but additionally a git version.
also I get `Result: failed with exit code 1` on any git operations with  `"git_binary": "bundled"`.

 Reason I want to use the bundled version is that I am on fedora silverblue and dont want to layer git-flow, but still want to use it.
What do I need to set to use the bundled version of git?

**Comment by ptomato** [comment]
Do you know where the bundled git binary is located in the flatpak's file system? (under `/app`) You could run a shell in the app's environment (`flatpak run --command=bash com.sublimemerge.App`) and see if you can run the bundled git binary from the command line.

**Comment by sennierer** [comment]
thanks, so running the git command in the flatpak works, but git flow doesnt seem to be installed.
I layered git flow and its working now on the system, but when I set `"git_binary": "system"` git flow is still not available. Is it possible that the flatpak just ignores the setting and always uses the bundled git version? And that the bundled git just doesnt include git flow?

**Comment by jwillikers** [comment]
From the perspective of Sublime Merge in the Flatpak, the `system` Git binary is actually the one installed inside the Flatpak. Giving the filesystem the `host` permission and attempting to run `/var/run/usr/bin/git` results in a fatal error regarding a `libc` mismatch, which is different between my host and the Flatpak runtime for Sublime Merge. Since Sublime Merge has specific support for Git Flow, we could probably add it to the Flatpak.

**Comment by sennierer** [comment]
ok, thanks. And yes, would be great to have git flow support in the flatpak of Sublime Merge!

**Comment by sennierer** [comment]
thanks very much for the fast fix! I can report that the git flow feature of the sublimemerge flatpak is now working as intended.
